### PR TITLE
Code Refactoring

### PR DESCRIPTION
**Pull request by Mouhamedtec**

### CODE REVIEW

**Comment by wolfadex** [comment]
@Mouhamedtec would you be able to elaborate on your changes here? I'm not as literate in Python and would like to forward this change request to our SDK team with as much context as possible.

**Comment by Mouhamedtec** [comment]
Hi, Mr Wolfgang Schuster

I'm so happy to get this response from your side and I will be happy to
clarify any information relative to the suggested changes, and I also wrote
a document for that particular solution.


https://drive.google.com/file/d/10-bjgbBnw6G9ZO3ckR7A7PTgG3TftwC1/view?usp=sharing

‫في الاثنين، 23 مايو 2022 في 4:14 م تمت كتابة ما يلي بواسطة ‪Wolfgang
Schuster‬‏ ***@***.***‬‏>:‬

**Comment by wolfadex** [comment]
@Mouhamedtec do you by chance have a GitHub gist or similar describing your changes? I can't download a PDF at work. Thank you for you time.

**Comment by Mouhamedtec** [comment]
Sure, here you go.
https://gist.github.com/Mouhamedtec/affc915457d376624a2885e3b0647f52

‫في الاثنين، 6 يونيو 2022 في 2:58 م تمت كتابة ما يلي بواسطة ‪Wolfgang
Schuster‬‏ ***@***.***‬‏>:‬

**Comment by wolfadex** [comment]
@Mouhamedtec thanks for the gist! I can't guarantee that these changes will be included but I'll pass the information along to our team that builds the SDK generation tools. We appreciate you taking the time to both make the PR and write out the reasoning.

**Comment by zenmasterjobo** [comment]
hi @Mouhamedtec - thanks for bringing up this up and taking the time to write a new class! Unfortunately we won't be bringing in these changes at this time. Thank you very much for your efforts!

**Pull request closed without merging**
